[GCP]
# Nom du dataset contenant les tables générées par l'algo de DEV
path=dsfr-frxxx-frxxxdev.EPSILON_DEV
dataset_id=EPSILON_DEV
project_id=dsfr-frxxx-frxxx-dev
[DATASET]
# Table contenant le périmètre des users
user=epsilon_perimetre_user_recommandation
